### ISSUE TITLE
[Question] Is it possible to acheive a SliverList behavior with this package while using multiple PaginatedFirestore?

### ISSUE THREAD

**Issue by dennysmvn** [vedartm/paginate_firestore#104]
Hi there, first of all thanks for your package!

I've created a page view with two PaginatedFirestore widgets, both with PaginateBuilderType.listView.

But now I wish to scroll the entire view, while also been able to scroll each one of listviews created by PaginatedFirestore.

Is it possible? I've been trying to use SliverList, CustomScrollView but all of their children needs to be a SliverRender...

I know this is not StackOverflow and I think it is possible to achieve this, but I'm realy struggling to find a way.

Thx!

**Comment by vedartm** [comment]
`PaginatedFirestore` is built with `CustomScrollView`. You find resources online to check how to use CustomScrollView inside a CustomScrollView

**Comment by WouterVandenputte** [comment]
I'm having the same question. I have a 'large' sliver appbar which for which i want to close the upper half when scrolling down and open it again on the first scroll up.
I have got it to work with just a list of 100 Text widgets, but cannot make it work with the PaginatedFirestore widget. Probably because it scrolls on its own and cannot be part of the larger picture.

@dennysmvn  Did you manage to find a solution?

**Comment by vedartm** [comment]
@WouterVandenputte you can put your appbar in the header and use the PaginatedFirestore as the base scroll.
